import { test,expect,type Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { readFileSync } from "node:fs";
import { bangkokInput } from "../src/lib/car-booking-display";
const base="http://localhost:3109";
async function login(page:Page,email:string) {
 await page.goto("/login");await page.locator('input[name="email"]').fill(email);await page.locator('input[name="password"]').fill("FixturePassword123!");await page.getByRole("button",{name:"เข้าสู่ระบบ",exact:true}).click();await expect(page).not.toHaveURL(/\/login/);
}
async function ready(page:Page){await expect(page.getByText("กำลังโหลดข้อมูล…",{exact:true})).toHaveCount(0);await expect(page.getByRole("button",{name:"โหลดใหม่",exact:true})).toBeEnabled();await expect(page.locator(".cb-error")).toHaveCount(0);}
test("desktop booking, logs with denied GPS, return validation, calendar privacy, keyboard and themes",async({page})=>{
 await login(page,"staff@car.example.test");await page.goto("/car-booking");await ready(page);
 await expect(page.getByRole("heading",{name:"ระบบจองรถ",exact:true})).toBeVisible();
 await page.locator(".cb-toolbar").getByRole("button",{name:"คืนรถ",exact:true}).click();await expect(page.getByText("รายการค้างจากเดือนก่อน",{exact:true})).toBeVisible();
 await page.locator(".cb-toolbar").getByRole("button",{name:"จองรถ",exact:true}).click();
 const destination=`ภารกิจทดสอบหน้าจอ ${Date.now()}`;const now=Date.now();await page.getByLabel("เวลาเริ่ม",{exact:true}).fill(bangkokInput(new Date(now)));await page.getByLabel("เวลากลับ",{exact:true}).fill(bangkokInput(new Date(now+30*60000)));await page.getByRole("button",{name:"ตรวจรถว่าง",exact:true}).click();
 await page.getByRole("combobox",{name:"ทะเบียนรถ",exact:true}).selectOption("00000000-0000-4000-8000-000000001202");await page.getByLabel("สถานที่ที่จะไป",{exact:true}).fill(destination);await page.getByRole("button",{name:"ยืนยันการจอง",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"จองรถเรียบร้อยแล้ว"})).toBeVisible();await ready(page);
 await page.locator(".cb-toolbar").getByRole("button",{name:"รายการของฉัน",exact:true}).click();const reservation=page.locator(".cb-reservation").filter({hasText:destination});await reservation.getByRole("button",{name:"เพิ่มบันทึก",exact:true}).click();
 const dialog=page.getByRole("dialog");await expect(dialog).toBeVisible();await page.keyboard.press("Escape");await expect(dialog).toHaveCount(0);await expect(reservation.getByRole("button",{name:"เพิ่มบันทึก",exact:true})).toBeFocused();
 await reservation.getByRole("button",{name:"เพิ่มบันทึก",exact:true}).click();await page.getByLabel("สถานที่",{exact:true}).fill("จุดแวะของฉัน");await page.getByLabel("เลขไมล์",{exact:true}).fill("110");
 await page.getByRole("button",{name:"แนบพิกัดปัจจุบัน",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"สามารถบันทึกต่อโดยไม่มีพิกัด"})).toBeVisible();await page.getByRole("button",{name:"บันทึกการเดินทาง",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"บันทึกระหว่างทางแล้ว"})).toBeVisible();await ready(page);
 await reservation.getByRole("button",{name:"คืนรถ",exact:true}).click();await expect(page.getByRole("combobox",{name:"ชั้นที่จอด",exact:true})).toHaveValue("2A");await page.getByLabel("เลขไมล์ตอนคืน",{exact:true}).fill("100");await page.getByRole("button",{name:"ยืนยันคืนรถ",exact:true}).click();await expect(dialog.locator("[role=alert]")).toContainText("เลขไมล์ต้องมากกว่าเลขไมล์ล่าสุด");
 await page.getByLabel("เลขไมล์ตอนคืน",{exact:true}).fill("120");await page.getByRole("button",{name:"ยืนยันคืนรถ",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"คืนรถเรียบร้อยแล้ว"})).toBeVisible();await ready(page);await expect(reservation).toContainText("คืนแล้ว");
 await page.locator(".cb-toolbar").getByRole("button",{name:"ปฏิทิน",exact:true}).click();await expect(page.locator(".cb-panel")).not.toContainText("ปลายทางส่วนตัวอื่น");await expect(page.locator(".cb-panel")).not.toContainText("ผู้ใช้อื่น");await expect(page.getByLabel("คำอธิบายสีรถ")).toContainText("ทดสอบ 1001");
 const payload=await page.request.get("/api/car-booking/calendar?start="+encodeURIComponent(new Date(now-86400000).toISOString())+"&end="+encodeURIComponent(new Date(now+86400000).toISOString()));expect(payload.status()).toBe(200);const data=await payload.json();expect(Object.keys(data.data[0]).sort()).toEqual(["car_id","end_time","license_plate","start_time"]);
 expect((await page.request.get("/api/car-booking/bookings/00000000-0000-4000-8000-000000001101/gps")).status()).toBe(403);
 await page.getByRole("combobox",{name:"มุมมองปฏิทิน",exact:true}).selectOption("week");await ready(page);await expect(page.locator(".cb-calendar-cell")).toHaveCount(7);await page.getByRole("combobox",{name:"มุมมองปฏิทิน",exact:true}).selectOption("day");await ready(page);await expect(page.locator(".cb-calendar-cell")).toHaveCount(1);await page.getByRole("button",{name:"ก่อนหน้า",exact:true}).click();await ready(page);await page.getByRole("button",{name:"วันนี้",exact:true}).click();await ready(page);await page.getByRole("combobox",{name:"มุมมองปฏิทิน",exact:true}).selectOption("month");await ready(page);const axe=await new AxeBuilder({page}).include(".cb-workspace").withTags(["wcag2a","wcag2aa","wcag21aa","wcag22aa"]).analyze();expect(axe.violations).toEqual([]);
 await page.screenshot({path:"docs/quality/car-booking-phase-4/desktop-light.png",fullPage:true});await page.evaluate(()=>{document.documentElement.dataset.theme="dark";});const dark=await new AxeBuilder({page}).include(".cb-workspace").withTags(["wcag2a","wcag2aa","wcag21aa","wcag22aa"]).analyze();expect(dark.violations).toEqual([]);await page.screenshot({path:"docs/quality/car-booking-phase-4/desktop-dark.png",fullPage:true});
});
test("admin-only access edits grant and revoke on the same live session without changing work access",async({browser})=>{
 const adminContext=await browser.newContext(),staffContext=await browser.newContext();const admin=await adminContext.newPage(),staff=await staffContext.newPage();
 try{
  await login(admin,"admin@car.example.test");await login(staff,"noaccess@car.example.test");await staff.goto("/car-booking");await expect(staff.locator(".access-denied")).toBeVisible();expect((await staff.request.get("/api/car-booking/cars")).status()).toBe(403);
  const session=(await staffContext.cookies()).find(cookie=>cookie.name==="pn_session")?.value;expect(session).toBeTruthy();
  await admin.goto("/admin/car-booking");await admin.getByLabel("ค้นหาผู้ใช้",{exact:true}).fill("noaccess@car.example.test");const row=admin.locator(".cb-access-row").filter({hasText:"noaccess@car.example.test"});await row.getByLabel("ใช้งาน",{exact:true}).check();await row.getByRole("button",{name:"บันทึกสิทธิ์ ผู้ใช้รอสิทธิ์",exact:true}).click();await expect(admin.getByRole("status")).toContainText("บันทึกสิทธิ์");
  await staff.reload();await ready(staff);await expect(staff.locator(".cb-toolbar").getByRole("button",{name:"จองรถ",exact:true})).toBeVisible();expect((await staff.request.get("/api/car-booking/cars")).status()).toBe(200);
  await row.getByLabel("ใช้งาน",{exact:true}).uncheck();const revoked=admin.waitForResponse(response=>response.url().endsWith("/api/admin/car-booking")&&response.request().method()==="PATCH");await row.getByRole("button",{name:"บันทึกสิทธิ์ ผู้ใช้รอสิทธิ์",exact:true}).click();expect((await revoked).status()).toBe(200);await expect(row.getByRole("checkbox",{name:"ใช้งาน",exact:true})).toBeEnabled();await expect(row.getByRole("button")).toBeDisabled();
  expect((await staff.request.get("/api/car-booking/cars")).status()).toBe(403);await staff.reload();await expect(staff.locator(".access-denied")).toBeVisible();await staff.goto("/work");await expect(staff).toHaveURL(/\/work/);await expect(staff.locator(".access-denied")).toHaveCount(0);expect((await staffContext.cookies()).find(cookie=>cookie.name==="pn_session")?.value).toBe(session);
  expect((await staff.request.patch("/api/admin/car-booking",{headers:{origin:base},data:{userId:"00000000-0000-4000-8000-000000001004",canUse:true,canAdmin:true,expectedUse:false,expectedAdmin:false}})).status()).toBe(403);
  const accessAxe=await new AxeBuilder({page:admin}).include(".cb-workspace").withTags(["wcag2a","wcag2aa","wcag21aa","wcag22aa"]).analyze();expect(accessAxe.violations).toEqual([]);await admin.screenshot({path:"docs/quality/car-booking-phase-4/access-management.png",fullPage:true});
 }finally{await adminContext.close();await staffContext.close();}
});
test("admin car editing, parking configuration and private GPS map",async({page})=>{
 await page.route("https://tile.openstreetmap.org/**",route=>route.fulfill({contentType:"image/png",body:Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=","base64")}));
 await login(page,"admin@car.example.test");await page.goto("/car-booking");await ready(page);
 await page.locator(".cb-toolbar").getByRole("button",{name:"จัดการรถ",exact:true}).click();await page.getByRole("button",{name:"เพิ่มรถ",exact:true}).click();const plate=`ทดสอบเพิ่ม ${Date.now()}`;await page.getByLabel("ทะเบียนรถ",{exact:true}).fill(plate);await page.getByLabel("เลขไมล์ล่าสุด",{exact:true}).fill("0");await page.getByRole("button",{name:"บันทึกรถ",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"บันทึกข้อมูลรถแล้ว"})).toBeVisible();await ready(page);
 await page.getByRole("button",{name:`แก้ไข ${plate}`,exact:true}).click();await page.getByLabel("เปิดใช้งานรถ",{exact:true}).uncheck();await page.getByRole("button",{name:"บันทึกรถ",exact:true}).click();await ready(page);await expect(page.getByRole("row").filter({hasText:plate})).toContainText("ปิดใช้งาน");
 await page.locator(".cb-toolbar").getByRole("button",{name:"ชั้นจอด",exact:true}).click();const floors=page.getByRole("textbox",{name:"ชั้นจอด (หนึ่งรายการต่อบรรทัด)",exact:true}),before=await floors.inputValue();await floors.fill(before+"\nZ9");await page.getByRole("button",{name:"บันทึกชั้นจอด",exact:true}).click();await ready(page);await expect(floors).toHaveValue(before+"\nZ9");await floors.fill(before);await page.getByRole("button",{name:"บันทึกชั้นจอด",exact:true}).click();await ready(page);
 await page.locator(".cb-toolbar").getByRole("button",{name:"การจองทั้งหมด",exact:true}).click();const other=page.locator(".cb-reservation").filter({hasText:"ปลายทางส่วนตัวอื่น"});await other.getByRole("button",{name:"ดูพิกัด",exact:true}).click();await expect(page.getByRole("img",{name:"แผนที่พิกัด จุดแวะทดสอบ",exact:true})).toBeVisible();await expect(page.getByRole("dialog")).toContainText("13.7500000, 100.5000000");await page.getByRole("dialog").screenshot({path:"docs/quality/car-booking-phase-4/gps-map.png"});await page.keyboard.press("Escape");
 const axe=await new AxeBuilder({page}).include(".cb-workspace").withTags(["wcag2a","wcag2aa","wcag21aa","wcag22aa"]).analyze();expect(axe.violations).toEqual([]);
});
test("mobile forms, cancellation confirmation and no horizontal page overflow",async({page})=>{
 await page.setViewportSize({width:390,height:844});await login(page,"staff@car.example.test");await page.goto("/car-booking");await ready(page);await expect(page.getByLabel("เวลาเริ่ม",{exact:true})).toBeVisible();
 const destination=`รายการมือถือยกเลิก ${Date.now()}`;const start=new Date(Date.now()+2*86400000),end=new Date(start.getTime()+3600000);await page.getByLabel("เวลาเริ่ม",{exact:true}).fill(bangkokInput(start));await page.getByLabel("เวลากลับ",{exact:true}).fill(bangkokInput(end));await page.getByRole("button",{name:"ตรวจรถว่าง",exact:true}).click();await page.getByRole("combobox",{name:"ทะเบียนรถ",exact:true}).selectOption("00000000-0000-4000-8000-000000001202");await page.getByLabel("สถานที่ที่จะไป",{exact:true}).fill(destination);await page.getByRole("button",{name:"ยืนยันการจอง",exact:true}).click();await ready(page);
 await page.locator(".cb-toolbar").getByRole("button",{name:"รายการของฉัน",exact:true}).click();const row=page.locator(".cb-reservation").filter({hasText:destination});await row.getByRole("button",{name:"ยกเลิกการจอง",exact:true}).click();await expect(page.getByRole("dialog")).toContainText(destination);await page.getByRole("button",{name:"ยืนยันยกเลิก",exact:true}).click();await ready(page);await expect(row).toContainText("ยกเลิก");
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
 const axe=await new AxeBuilder({page}).include(".cb-workspace").withTags(["wcag2a","wcag2aa","wcag21aa","wcag22aa"]).analyze();expect(axe.violations).toEqual([]);await page.screenshot({path:"docs/quality/car-booking-phase-4/mobile.png",fullPage:true});await page.evaluate(()=>{document.documentElement.dataset.theme="dark";});const mobileDark=await new AxeBuilder({page}).include(".cb-workspace").withTags(["wcag2a","wcag2aa","wcag21aa","wcag22aa"]).analyze();expect(mobileDark.violations).toEqual([]);await page.screenshot({path:"docs/quality/car-booking-phase-4/mobile-dark.png",fullPage:true});
});
test("anonymous API and forced-password account are denied",async({page})=>{
 expect((await page.request.get("/api/car-booking/cars")).status()).toBe(401);await login(page,"temporary@car.example.test");await expect(page).toHaveURL(/\/change-password/);expect(await page.evaluate(async()=> (await fetch("/api/car-booking/cars")).status)).toBe(403);
});
test("admin OSP download, shared dashboard totals, queue controls and responsive report accessibility",async({page})=>{
 await login(page,"admin@car.example.test");await page.goto("/car-booking");await ready(page);
 await page.locator(".cb-toolbar").getByRole("button",{name:"รายงาน OSP",exact:true}).click();await expect(page.getByText("กำลังโหลดรายงาน…",{exact:true})).toHaveCount(0);await expect(page.getByRole("button",{name:"โหลดรายงานใหม่",exact:true})).toBeEnabled();
 const row=page.locator(".cb-report tbody tr").filter({hasText:"ภารกิจรายงาน OSP"});await expect(row).toBeVisible();await expect(row.locator("td").nth(4)).toHaveText("0");await expect(row.locator("td").nth(8)).toHaveText("100");await expect(row.locator("td").nth(16)).toHaveText("40");await expect(row.locator("td").nth(17)).toHaveText("1600");
 const scroll=page.locator(".cb-osp-table").locator("..");await scroll.focus();await page.keyboard.press("ArrowRight");await expect.poll(()=>scroll.evaluate(element=>element.scrollLeft)).toBeGreaterThan(0);await scroll.evaluate(element=>{element.scrollLeft=0;});
 const downloadWait=page.waitForEvent("download");await page.getByRole("link",{name:"ดาวน์โหลด OSP CSV",exact:true}).click();const download=await downloadWait;expect(download.suggestedFilename()).toMatch(/^OSP-.*\.csv$/);const csv=readFileSync((await download.path())!,"utf8");expect(csv.startsWith("\ufeff")).toBe(true);expect(csv).toContain('"40","1600"');expect(csv).toContain("ภารกิจรายงาน OSP");
 await page.getByText("สร้างรายงานทั้งชีตใหม่",{exact:true}).click();await page.getByRole("button",{name:"ยืนยันสร้างรายงานทั้งชีตใหม่",exact:true}).click();await expect(page.getByRole("status").filter({hasText:"รับคำขอแล้ว"})).toBeVisible();await expect(page.getByRole("button",{name:"โหลดรายงานใหม่",exact:true})).toBeEnabled();
 const axe=await new AxeBuilder({page}).include(".cb-report").withTags(["wcag2a","wcag2aa","wcag21aa","wcag22aa"]).analyze();expect(axe.violations).toEqual([]);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:"docs/quality/car-booking-phase-4/report-light.png",fullPage:true});await page.evaluate(()=>{document.documentElement.dataset.theme="dark";});expect((await new AxeBuilder({page}).include(".cb-report").withTags(["wcag2a","wcag2aa","wcag21aa","wcag22aa"]).analyze()).violations).toEqual([]);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:"docs/quality/car-booking-phase-4/report-dark.png",fullPage:true});
 await page.locator(".cb-toolbar").getByRole("button",{name:"แดชบอร์ด",exact:true}).click();await expect(page.getByRole("button",{name:"โหลดรายงานใหม่",exact:true})).toBeEnabled();await expect(page.locator(".cb-stats")).toContainText("1600");await page.screenshot({path:"docs/quality/car-booking-phase-4/dashboard.png",fullPage:true});
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);expect((await new AxeBuilder({page}).include(".cb-report").withTags(["wcag2a","wcag2aa","wcag21aa","wcag22aa"]).analyze()).violations).toEqual([]);await page.screenshot({path:"docs/quality/car-booking-phase-4/dashboard-mobile.png",fullPage:true});
 await page.locator(".cb-toolbar").getByRole("button",{name:"รายงาน OSP",exact:true}).click();await expect(page.getByRole("button",{name:"โหลดรายงานใหม่",exact:true})).toBeEnabled();
 for(const theme of ["light","dark"]){await page.evaluate(value=>{document.documentElement.dataset.theme=value;},theme);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);expect((await new AxeBuilder({page}).include(".cb-report").withTags(["wcag2a","wcag2aa","wcag21aa","wcag22aa"]).analyze()).violations).toEqual([]);await page.screenshot({path:`docs/quality/car-booking-phase-4/report-mobile-${theme}.png`,fullPage:true});}
});
test("staff cannot read/export OSP or dashboard, and scheduler authentication fails closed",async({page})=>{
 await login(page,"staff@car.example.test");await page.goto("/car-booking");await ready(page);await expect(page.locator(".cb-toolbar").getByRole("button",{name:"รายงาน OSP",exact:true})).toHaveCount(0);
 for(const path of ["/api/car-booking/reports?month=all","/api/car-booking/reports?format=csv","/api/car-booking/dashboard","/api/car-booking/osp-sync"])expect((await page.request.get(path)).status()).toBe(403);
 expect((await page.request.post("/api/car-booking/osp-sync",{headers:{origin:base},data:{action:"rebuild"}})).status()).toBe(403);
 expect((await page.request.post("/api/internal/car-booking/osp")).status()).toBe(503);
});
