"use client";
import { useActionState, useState } from "react";
import { saveWorkAdminAction, previewWorkAdminAction, confirmWorkAdminAction, type WorkAdminState } from "@/app/(platform)/admin/work-actions";
import { restoreWorkTaskAction, type WorkActionState } from "@/app/(platform)/work/actions";
import type { WorkAdminData } from "@/lib/work-admin-read";
const initial:WorkAdminState={ ok:false,message:"" };
function AdminForm({ kind,title,children }: { kind:string;title:string;children:React.ReactNode }) {
  const [state,action,pending]=useActionState(saveWorkAdminAction,initial);
  return <form action={action} className="work-admin-form"><h3>{title}</h3><input type="hidden" name="kind" value={kind}/><fieldset disabled={pending}>{children}</fieldset><div className="work-action-row"><button className="primary" disabled={pending}>{pending ? "กำลังบันทึก…":"บันทึก"}</button><button className="secondary-action" type="reset" disabled={pending}>ล้างฟอร์ม</button></div><p role="status">{state.message}</p></form>;
}
function Version({ id,version }: { id?:string;version?:number }) {return <><input type="hidden" name="id" value={id ?? ""}/><input type="hidden" name="expectedVersion" value={version ?? ""}/></>;}
function CalendarPanel({ data }: { data:WorkAdminData }) {
  const [edit,setEdit]=useState<WorkAdminData["calendar"][number]|undefined>();
  const [year,setYear]=useState("");const [source,setSource]=useState("");const [active,setActive]=useState("");
  const rows=data.calendar.filter(r=>(!year||r.holidayDate.startsWith(year))&&(!source||r.source===source)&&(!active||String(r.isActive)===active));
  return <section id="calendar" className="admin-panel"><h2>วันหยุด</h2><p>เพิ่มวันหยุดบริษัทหรือวันหยุดไทยด้วยมือ แล้วดูผลกระทบก่อนคำนวณกำหนดใหม่</p><div className="work-form-grid"><label>ปี<input value={year} onChange={e=>setYear(e.target.value)} placeholder="2026"/></label><label>แหล่งที่มา<select value={source} onChange={e=>setSource(e.target.value)}><option value="">ทั้งหมด</option><option value="company">บริษัท</option><option value="thai">วันหยุดไทย</option></select></label><label>สถานะ<select value={active} onChange={e=>setActive(e.target.value)}><option value="">ทั้งหมด</option><option value="true">ใช้งาน</option><option value="false">ปิดใช้งาน</option></select></label></div><ul>{rows.map(r=><li key={r.id}>{r.holidayDate} · {r.name} · {r.isActive?"ใช้งาน":"ปิดใช้งาน"} <button type="button" className="text-btn" onClick={()=>setEdit(r)}>แก้ไข / ปิดใช้งาน</button></li>)}</ul><button type="button" className="secondary-action" onClick={()=>setEdit(undefined)}>เพิ่มวันหยุด</button><AdminForm key={`${edit?.id}:${edit?.version}`} kind="holiday" title={edit?"แก้ไขวันหยุด":"เพิ่มวันหยุด"}><Version id={edit?.id} version={edit?.version}/><label>วันที่<input name="holidayDate" type="date" required defaultValue={edit?.holidayDate}/></label><label>ชื่อวันหยุด<input name="name" required maxLength={180} defaultValue={edit?.name}/></label><label>แหล่งที่มา<select name="source" defaultValue={edit?.source??"company"}><option value="company">บริษัท</option><option value="thai">วันหยุดไทย</option></select></label><label><input type="checkbox" name="isActive" defaultChecked={edit?.isActive??true}/> ใช้งาน</label></AdminForm></section>;
}
function KpiPanel({ data }: { data:WorkAdminData }) {
  const [edit,setEdit]=useState<WorkAdminData["catalog"][number]|undefined>();
  return <section id="kpi" className="admin-panel"><h2>กฎ KPI / SLA</h2><p>แต่ละการบันทึกสร้าง version ใหม่ งานเก่าเก็บกฎที่ใช้เดิม การปิดใช้งานยังรักษาประวัติไว้</p><ul>{data.catalog.map(r=><li key={r.id}>{r.mainKpi} / {r.subKpi} · {r.slaDays} วันทำการ · น้ำหนัก {r.mainWeight} · รุ่น {r.version} · {r.status==="active"?"ใช้งาน":"ปิดใช้งาน"} <button type="button" className="text-btn" onClick={()=>setEdit(r)}>แก้ไข / ปิดใช้งาน</button></li>)}</ul><button type="button" className="secondary-action" onClick={()=>setEdit(undefined)}>เพิ่มกฎ</button><AdminForm key={`${edit?.id}:${edit?.version}`} kind="rule" title={edit?"สร้างรุ่นใหม่":"เพิ่ม KPI"}><input type="hidden" name="metricId" value={edit?.metricId??""}/><input type="hidden" name="expectedVersion" value={edit?.version??0}/><label>ทีม<select name="teamId" defaultValue={edit?.teamId??""} required><option value="">เลือกทีม</option>{data.teams.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Main KPI<input name="mainKpi" required maxLength={180} defaultValue={edit?.mainKpi}/></label><label>Sub KPI<input name="subKpi" required maxLength={180} defaultValue={edit?.subKpi}/></label><label>SLA (วันทำการ)<input name="slaDays" type="number" min={0} max={366} required defaultValue={edit?.slaDays}/></label><label>น้ำหนัก Main KPI<input name="mainWeight" type="number" step="0.000001" min="0.000001" max={100} required defaultValue={edit?.mainWeight}/></label><label><input type="checkbox" name="active" defaultChecked={edit?.status!=="retired"}/> ใช้งาน</label></AdminForm></section>;
}
function PersonalPanel({ data }: { data:WorkAdminData }) {
  const [personKey,setPersonKey]=useState("");const [all,setAll]=useState(false);
  const person=data.people.find(p=>`${p.id}:${p.teamId}`===personKey);
  const latest=data.personals.find(p=>p.userId===person?.id&&p.teamId===person?.teamId);
  const catalog=data.catalog.filter(r=>r.teamId===person?.teamId&&r.status==="active");
  return <section id="personal-kpi" className="admin-panel"><h2>KPI รายบุคคล</h2><label>ผู้รับผิดชอบ<select value={personKey} onChange={e=>{setPersonKey(e.target.value);setAll(false);}}><option value="">เลือกผู้รับผิดชอบ</option>{data.people.map(p=><option key={`${p.id}:${p.teamId}`} value={`${p.id}:${p.teamId}`}>{p.name} · {data.teams.find(t=>t.id===p.teamId)?.name}</option>)}</select></label>{person&&<AdminForm key={`${personKey}:${latest?.version}:${all}`} kind="personal" title="น้ำหนักของคนนี้ (%)"><input type="hidden" name="userId" value={person.id}/><input type="hidden" name="teamId" value={person.teamId}/><input type="hidden" name="expectedVersion" value={latest?.version??0}/><p>น้ำหนักที่เลือกใช้ต้องรวมเป็น 100% การเปลี่ยนแปลงสร้างรุ่นใหม่และไม่แก้น้ำหนักงานเก่า</p><button type="button" className="secondary-action" onClick={()=>setAll(true)}>ใช้ KPI ที่แสดงทั้งหมด</button>{catalog.map(r=>{ const previous=latest?.assignments.find(a=>a.metricId===r.metricId);return <div key={r.metricId} className="work-personal-kpi-row"><input type="hidden" name="metricIds" value={r.metricId}/><label><input type="checkbox" name={`enabled:${r.metricId}`} defaultChecked={all||previous?.enabled||false}/> ใช้กับคนนี้ · {r.mainKpi} / {r.subKpi}</label><label>น้ำหนักของคนนี้ (%)<input type="number" name={`weight:${r.metricId}`} min="0.000001" max={100} step="0.000001" defaultValue={previous?.weight??r.mainWeight} required/></label></div>;})}</AdminForm>}</section>;
}
function RecalculationPanel({ kind }: { kind:"deadlines"|"kpi_migration" }) {
  const [preview,previewAction,previewPending]=useActionState(previewWorkAdminAction,initial);
  const [result,confirmAction,confirmPending]=useActionState(confirmWorkAdminAction,initial);
  return <section className="admin-panel"><h2>{kind==="deadlines"?"คำนวณกำหนดส่งใหม่":"ย้าย KPI งานเก่า — ตัวอย่างเท่านั้น"}</h2><form action={previewAction}><input type="hidden" name="kind" value={kind}/><button className="secondary-action" disabled={previewPending||confirmPending}>{previewPending?"กำลังตรวจผลกระทบ…":"ดูตัวอย่างผลกระทบ"}</button></form><p role="status">{preview.message}</p>{preview.rows&&<><div className="admin-table-wrap"><table><caption>รายการที่จะได้รับผลกระทบ</caption><thead><tr><th scope="col">งาน</th><th scope="col">เดิม</th><th scope="col">ใหม่</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.taskId}><td>{r.title}</td><td>{kind==="deadlines"?r.beforeDueAt:r.beforeWeight}</td><td>{kind==="deadlines"?r.afterDueAt:r.afterWeight}</td></tr>)}</tbody></table></div>{kind==="deadlines"&&preview.rows.length>0&&<form action={confirmAction}><input type="hidden" name="previewId" value={preview.previewId}/><label><input type="checkbox" name="confirm" required/> ยืนยันรายการข้างต้น (ตัวอย่างมีอายุ 15 นาที)</label><button className="primary" disabled={confirmPending||previewPending||result.ok}>{confirmPending?"กำลังคำนวณ…":"ยืนยันคำนวณใหม่"}</button><p role="status">{result.message}</p></form>}</>}</section>;
}
function SystemsPanel({ data }: { data:WorkAdminData }) {
  const [edit,setEdit]=useState<Partial<WorkAdminData["links"][number]>|undefined>();const [revision,setRevision]=useState(0);
  function choose(value:typeof edit){setEdit(value);setRevision(r=>r+1);}
  return <section id="systems" className="admin-panel"><h2>ลิงก์ระบบ</h2><ul>{data.links.map(r=><li key={r.id}>{r.name} · {r.status} <button type="button" className="text-btn" onClick={()=>choose(r)}>แก้ไข / ซ่อน</button> <button type="button" className="text-btn" onClick={()=>choose({...r,id:undefined,version:undefined,name:`${r.name} (สำเนา)`})}>Duplicate</button></li>)}</ul><button type="button" className="secondary-action" onClick={()=>choose(undefined)}>เพิ่ม / ล้างฟอร์ม</button><AdminForm key={revision} kind="system" title={edit?.id?"แก้ไขลิงก์":"เพิ่มลิงก์"}><Version id={edit?.id} version={edit?.version}/><label>ชื่อ<input name="name" required maxLength={180} defaultValue={edit?.name}/></label><label>คำอธิบาย<textarea name="description" maxLength={1000} defaultValue={edit?.description}/></label><label>URL<input name="url" required maxLength={2000} defaultValue={edit?.url} placeholder="https:// หรือ /path"/></label><label>ไอคอน<input name="icon" defaultValue={edit?.icon??"link"} maxLength={80}/></label><label>สถานะ<select name="status" defaultValue={edit?.status??"Active"}><option>Active</option><option>Maintenance</option><option>Coming Soon</option><option>Hidden</option></select></label><label><input type="checkbox" name="visibleToAll" defaultChecked={edit?.visibleToAll}/> แสดงให้ผู้ใช้ทุกคน</label><fieldset><legend>บทบาทที่ดูได้</legend>{data.roles.map(r=><label key={r.id}><input type="checkbox" name="roleIds" value={r.id} defaultChecked={edit?.roleIds?.includes(r.id)}/> {r.name}</label>)}</fieldset><fieldset><legend>ทีมที่ดูได้</legend>{data.teams.map(r=><label key={r.id}><input type="checkbox" name="teamIds" value={r.id} defaultChecked={edit?.teamIds?.includes(r.id)}/> {r.name}</label>)}</fieldset></AdminForm></section>;
}
function RestoreForm({ task }: { task:WorkAdminData["deleted"][number] }) {
  const [state,action,pending]=useActionState(restoreWorkTaskAction,{ok:false,message:""} as WorkActionState);
  return <form action={action}><span>{task.title}</span><input type="hidden" name="taskId" value={task.id}/><input type="hidden" name="version" value={task.version}/><input type="hidden" name="idempotencyKey" value={`restore:${task.id}:${task.version}`}/><label>เหตุผลที่กู้คืน<input name="reason" required maxLength={1000}/></label><button className="secondary-action" disabled={pending}>กู้คืนงาน</button><p role="status">{state.message}</p></form>;
}
export function WorkAdminPanels({ data,section }: { data:WorkAdminData;section:string }) {
  return <div className="work-admin-panels">
    {data.granted.kpi&&section==="kpi"&&<KpiPanel data={data}/>}
    {data.granted.kpi&&section==="personal-kpi"&&<PersonalPanel data={data}/>}
    {data.granted.kpi&&section==="recalculate"&&<><RecalculationPanel kind="deadlines"/><RecalculationPanel kind="kpi_migration"/></>}
    {data.granted.calendar&&section==="calendar"&&<CalendarPanel data={data}/>} {data.granted.systems&&section==="systems"&&<SystemsPanel data={data}/>}
    {data.granted.announcement&&section==="announcement"&&<section id="announcement" className="admin-panel"><h2>ประกาศแอดมิน</h2>{data.announcements.map(r=><AdminForm key={`${r.id}:${r.version}`} kind="announcement" title="แก้ไขประกาศ"><Version id={r.id} version={r.version}/><label>ข้อความ<textarea name="message" defaultValue={r.message} maxLength={4000}/></label><label><input name="isActive" type="checkbox" defaultChecked={r.isActive}/> แสดงบนหน้าหลัก</label></AdminForm>)}<AdminForm kind="announcement" title="เพิ่มประกาศ"><label>ข้อความ<textarea name="message" required maxLength={4000}/></label><label><input name="isActive" type="checkbox"/> แสดงบนหน้าหลัก</label></AdminForm></section>}
    {section==="restore"&&<section className="admin-panel"><h2>กู้คืนงานที่ลบ</h2>{data.deleted.length?data.deleted.map(task=><RestoreForm key={task.id} task={task}/>):<p className="admin-empty">ไม่มีงานที่รอกู้คืนในขอบเขตสิทธิ์ของคุณ</p>}</section>}
  </div>;
}
