import Link from "next/link";
import { taskCapabilities } from "@/lib/work-task-policy";
import { type AuthorizationSubject } from "@/lib/authorization";
import { formatWorkspaceDate } from "@/lib/workspace-view";
import type { WorkTaskRecord } from "@/lib/work-read-model";
import { StatusBadge } from "@/components/ui/status-badge";
import { TaskActionControls, TaskNoteForm } from "@/features/work/components/task-actions";

export function WorkTaskTable({ tasks, subject, showNotes = false }: { tasks: WorkTaskRecord[]; subject?: AuthorizationSubject; showNotes?: boolean }) {
  if (!tasks.length) return null;
  return <div className="work-table-wrap" role="region" aria-label="รายการงาน เลื่อนแนวนอนได้" tabIndex={0}><table className="work-data-table"><caption className="sr-only">รายการงานในขอบเขตสิทธิ์ของคุณ</caption><thead><tr><th scope="col">งาน / Job</th><th scope="col">ผู้รับผิดชอบ</th><th scope="col">KPI</th><th scope="col">กำหนด</th><th scope="col">สถานะ</th><th scope="col">คำสั่ง</th></tr></thead><tbody>{tasks.map((task) => { const caps = taskCapabilities(subject, task); return <tr key={task.id}><td><Link className="work-task-link" href={`/work?record=${task.id}`}>{task.title}</Link><span className="work-task-meta">{task.jobCode || "ยังไม่มีรหัสงาน"} · อัปเดต {formatWorkspaceDate(task.updatedAt)}</span>{showNotes && <span className="work-task-note">{task.note || "ยังไม่มีบันทึกเพิ่มเติม"}</span>}</td><td>{task.ownerName}<span className="work-task-meta">{task.teamName}</span></td><td><span>{task.mainKpi || "ยังไม่ระบุ"}</span><span className="work-task-meta">{task.subKpi || "ยังไม่มี Sub KPI"}</span></td><td>{task.dueAt ? formatWorkspaceDate(task.dueAt) : "ไม่กำหนด"}</td><td><StatusBadge label={task.statusLabel} tone={task.status === "completed" ? "success" : task.status === "blocked" ? "warning" : task.status === "cancelled" ? "danger" : task.status === "in_progress" ? "info" : "neutral"}/></td><td>{(caps.update || caps.delete) ? <TaskActionControls task={task} capabilities={caps}/> : <span className="work-action-muted">ดูอย่างเดียว</span>}</td></tr>})}</tbody></table></div>;
}

export function WorkTaskDetail({ task, subject }: { task: WorkTaskRecord; subject?: AuthorizationSubject }) {
  const caps = taskCapabilities(subject, task);
  return <article className="work-task-detail"><div className="work-task-detail-head"><div><span className="work-eyebrow">{task.jobCode || "งานที่ไม่มีรหัส"}</span><h2>{task.title}</h2><p>{task.description || "ยังไม่มีรายละเอียดงาน"}</p></div><StatusBadge label={task.statusLabel} tone={task.status === "completed" ? "success" : task.status === "blocked" ? "warning" : task.status === "cancelled" ? "danger" : "info"}/></div><dl className="work-detail-grid"><div><dt>ผู้รับผิดชอบ</dt><dd>{task.ownerName}</dd></div><div><dt>ทีม</dt><dd>{task.teamName}</dd></div><div><dt>Main KPI</dt><dd>{task.mainKpi || "ยังไม่ระบุ"}</dd></div><div><dt>Sub KPI</dt><dd>{task.subKpi || "ยังไม่ระบุ"}</dd></div><div><dt>กำหนด</dt><dd>{task.dueAt ? formatWorkspaceDate(task.dueAt) : "ไม่กำหนด"}</dd></div><div><dt>น้ำหนัก</dt><dd>{task.kpiWeight || "ยังไม่ระบุจากกฎ KPI"}</dd></div></dl>{task.notes?.length ? <section><h3>บันทึกที่ผ่านมา</h3><ul>{task.notes.map(note=><li key={note.id}>{formatWorkspaceDate(note.createdAt)} · {note.body}</li>)}</ul></section> : null}{(caps.update || caps.note || caps.delete) ? <><TaskActionControls task={task} capabilities={caps}/>{caps.note && <TaskNoteForm task={task}/>}</> : <p className="work-action-muted">บัญชีนี้มีสิทธิ์ดูรายละเอียด แต่ยังไม่มีสิทธิ์เปลี่ยนแปลงงาน</p>}</article>;
}
