"use client";

import { useActionState } from "react";
import type { WorkReadModel } from "@/lib/work-read-model";
import { assignWorkTasksAction, type WorkActionState } from "@/app/(platform)/work/actions";
import { WorkEmpty, WorkScreenShell, WorkUnavailable } from "@/features/work/components/work-screen-shell";

const initial: WorkActionState = { ok: false, message: "" };

export function AssignmentCenterScreen({ model }: { model: WorkReadModel }) {
  const [state, action, pending] = useActionState(assignWorkTasksAction, initial);
  return <WorkScreenShell title="ศูนย์มอบหมายงาน" description="มอบหมายหลายงานในครั้งเดียว พร้อมตรวจทีม ผู้รับผิดชอบ และรหัสงานซ้ำก่อนบันทึก" parent={{ label: "ภาพรวมทีม", href: "/work/team" }}>
    {model.source.status !== "ready" ? <WorkUnavailable message="ยังโหลดข้อมูลสำหรับการมอบหมายไม่ได้" detail={model.source.message} /> : model.assignmentOptions.length ? <form action={action} className="work-panel work-assignment-form"><div className="work-form-intro"><div><span className="work-eyebrow">Assignment Center</span><h2>มอบหมายงานให้ทีม</h2><p>กรอกหนึ่งรหัสงานต่อหนึ่งบรรทัด ระบบจะป้องกันรหัสซ้ำในทีมและบันทึกกิจกรรมการมอบหมาย</p></div><span className="work-form-count">ผู้รับผิดชอบ {model.assignmentOptions.length} คน</span></div><div className="work-form-grid"><label>ผู้รับผิดชอบ<select name="assigneeId" required defaultValue=""><option value="" disabled>เลือกผู้รับผิดชอบ</option>{model.assignmentOptions.map((person) => <option key={person.id} value={person.id}>{person.name} · {person.teamName}</option>)}</select></label><label>ทีม<select name="teamId" required defaultValue=""><option value="" disabled>เลือกทีม</option>{[...new Map(model.assignmentOptions.filter((person) => person.teamId).map((person) => [person.teamId, person.teamName])).entries()].map(([id, name]) => <option key={id} value={id!}>{name}</option>)}</select></label><label>ชื่อชุดงาน<input name="title" required minLength={3} maxLength={180} placeholder="เช่น ตรวจสอบเอกสารประจำเดือน" /></label><label>Main KPI<input name="mainKpi" maxLength={180} placeholder="เลือกเมื่อมีกฎที่อนุมัติแล้ว" /></label><label>Sub KPI<input name="subKpi" maxLength={180} placeholder="เลือกเมื่อมีกฎที่อนุมัติแล้ว" /></label><label>กำหนดส่ง<input name="dueAt" type="date" /></label><label>ระดับความเร่งด่วน<select name="priority" defaultValue="normal"><option value="low">ต่ำ</option><option value="normal">ปกติ</option><option value="high">สูง</option><option value="urgent">เร่งด่วน</option></select></label><label className="work-form-span-2">รหัสงาน / งานย่อย<textarea name="jobs" rows={5} required placeholder="JOB-001&#10;JOB-002" /></label><label className="work-form-span-2">หมายเหตุ<textarea name="notes" rows={4} maxLength={4000} placeholder="ข้อมูลที่ผู้รับผิดชอบควรรู้" /></label></div>{state.message && <p className={state.ok ? "work-action-success" : "work-action-error"} role="status">{state.message}</p>}<div className="work-form-actions"><button className="primary" disabled={pending}>{pending ? "กำลังมอบหมาย…" : "ตรวจสอบและมอบหมาย"}</button><p>น้ำหนัก KPI และกฎ SLA จะมาจากข้อมูลที่อนุมัติในระบบ ไม่เติมค่าแทนโดยอัตโนมัติ</p></div></form> : <WorkEmpty title="ยังไม่มีผู้รับผิดชอบที่อยู่ในขอบเขต" detail="ตรวจสอบสิทธิ์ทีมของคุณ หรือให้ผู้ดูแลเพิ่มผู้ใช้และขอบเขตการมอบหมายก่อน" />}
  </WorkScreenShell>;
}
