import type { WorkReadModel } from "@/lib/work-read-model";
import { WorkEmpty, WorkScreenShell, WorkUnavailable } from "@/features/work/components/work-screen-shell";
import { formatWorkspaceDate } from "@/lib/workspace-view";

export function KpiWorkspaceScreen({ model }: { model: WorkReadModel }) {
  if (model.source.status !== "ready") return <WorkScreenShell title="KPI ของฉัน" description="ดูผลการทำงานและหลักฐานที่นำไปคำนวณ"><WorkUnavailable message="ยังโหลด KPI ไม่ได้" detail={model.source.message} /></WorkScreenShell>;
  return <WorkScreenShell title="KPI ของฉัน" description="เข้าใจคะแนนจากงานจริง เป้าหมาย ช่วงเวลา และ SLA โดยไม่ต้องอ่านรหัสภายใน" parent={{ label: "งานและ KPI", href: "/work" }}>
    {model.personalAssignments.length > 0 && <section className="work-panel"><h2>กฎและน้ำหนัก KPI ของฉัน</h2><ul>{model.personalAssignments.map((row,i)=><li key={i}>{row.name} · {row.weight}% · รุ่น {row.version} · {row.enabled ? "ใช้งาน" : "ไม่ใช้"}</li>)}</ul><p>กฎนี้ใช้กับงานใหม่ งานเดิมเก็บน้ำหนักและกฎที่ใช้ตอนสร้าง</p></section>}{model.kpiCards.length ? <section className="work-kpi-business-grid">{model.kpiCards.map((card) => <article className="work-kpi-business-card" key={card.id}><div className="work-kpi-card-head"><div><span className="work-eyebrow">ตัวชี้วัด</span><h2>{card.metric}</h2></div><strong>{card.actual} <small>{card.unit}</small></strong></div><dl><div><dt>เป้าหมาย</dt><dd>{card.target ?? "ยังไม่มีเป้าหมายที่อนุมัติ"}</dd></div><div><dt>ความคืบหน้า</dt><dd>{card.progress === null ? "ยังคำนวณไม่ได้" : `${card.progress}%`}</dd></div><div><dt>ช่วงเวลา</dt><dd>{formatWorkspaceDate(card.periodStart)} – {formatWorkspaceDate(card.periodEnd)}</dd></div><div><dt>หลักฐานงาน</dt><dd>{card.factCount.toLocaleString("th-TH")} รายการ</dd></div><div><dt>น้ำหนัก</dt><dd>{card.weight ?? "ยังไม่มีน้ำหนักจากกฎที่อนุมัติ"}</dd></div></dl><p className="work-kpi-footnote">คำนวณล่าสุด {formatWorkspaceDate(card.calculatedAt, true)}</p></article>)}</section> : <WorkEmpty title="ยังไม่มีผล KPI ที่เผยแพร่" detail="เมื่อมีผลคำนวณจากกฎและข้อมูลที่อนุมัติแล้ว ระบบจะแสดงเป้าหมาย ผลจริง ความคืบหน้า และงานที่นำมาคิดที่นี่" />}
    {model.facts.length > 0 && <section className="work-panel"><div className="work-section-head"><div><h2>หลักฐานที่ใช้คำนวณ</h2><p>รายละเอียดทางเทคนิคอยู่ในส่วนตรวจสอบ และไม่รบกวนการอ่าน KPI หลัก</p></div></div><details className="work-technical-details"><summary>เปิดรายละเอียดตรวจสอบ</summary><div className="work-table-wrap"><table className="work-data-table"><thead><tr><th>ตัวชี้วัด</th><th>ค่า</th><th>สถานะ</th><th>วันที่</th><th>เวอร์ชันการคำนวณ</th></tr></thead><tbody>{model.facts.map((fact) => <tr key={fact.id}><td>{fact.metric}</td><td>{fact.value}</td><td>{fact.status === "applied" ? "นำไปคำนวณ" : "กลับรายการ"}</td><td>{formatWorkspaceDate(fact.occurredAt)}</td><td>{fact.calculationVersion}</td></tr>)}</tbody></table></div></details></section>}
  </WorkScreenShell>;
}
