import { copy } from "@/lib/copy";
import type { WorkReadModel } from "@/lib/work-read-model";
import { WorkEmpty, WorkMetricStrip, WorkScreenShell, WorkUnavailable } from "@/features/work/components/work-screen-shell";

export function WorkReportsScreen({ model }: { model: WorkReadModel }) {
  if (model.source.status !== "ready") return <WorkScreenShell title="รายงานงาน" description="สรุปงานตามสถานะ คน ทีม และ SLA"><WorkUnavailable message="ยังโหลดรายงานไม่ได้" detail={model.source.message} /></WorkScreenShell>;
  return <WorkScreenShell title="รายงานงาน" description="สรุปความคืบหน้าและ SLA ด้วยค่าที่มาจากงานในขอบเขตสิทธิ์" parent={{ label: "งานและ KPI", href: "/work" }}>
    <WorkMetricStrip metrics={[{ label: "งานทั้งหมด", value: model.report.taskCount, detail: "รายการที่เข้าถึงได้" }, { label: "ความสำเร็จถ่วงน้ำหนัก", value: model.report.completion === null ? "—" : `${model.report.completion}%`, detail: "ไม่รวมงานที่ยกเลิก", tone: "success" }, { label: "SLA ถ่วงน้ำหนัก", value: model.report.sla === null ? "—" : `${model.report.sla}%`, detail: "จากงานที่เสร็จสิ้น", tone: "info" }, { label: "เกินกำหนด", value: model.report.overdue, detail: "ต้องติดตาม", tone: "danger" }]} />
    {model.report.taskCount ? <div className="work-report-layout"><section className="work-panel"><div className="work-section-head"><div><h2>สถานะงาน</h2><p>{copy.feedback.workStatusDescription}</p></div></div><div className="work-status-list">{Object.entries(model.statusCounts).map(([status, count]) => <div key={status}><span>{status}</span><strong>{count.toLocaleString("th-TH")}</strong><div className="work-status-bar"><span style={{ width: `${Math.min(100, (count / Math.max(1, model.report.taskCount)) * 100)}%` }} /></div></div>)}</div></section><section className="work-panel"><div className="work-section-head"><div><h2>สิ่งที่ควรติดตาม</h2><p>ช่วยจัดลำดับงานก่อนลงรายละเอียดรายคนหรือราย Job</p></div></div><dl className="work-report-detail"><div><dt>ใกล้ครบกำหนดภายใน 3 วัน</dt><dd>{model.report.dueSoon}</dd></div><div><dt>เกินกำหนด</dt><dd className={model.report.overdue ? "work-danger-text" : ""}>{model.report.overdue}</dd></div><div><dt>น้ำหนักรวม</dt><dd>{model.weightedReport.totalWeight}</dd></div></dl></section></div> : <WorkEmpty title="ยังไม่มีข้อมูลสำหรับรายงาน" detail="รายงานจะแสดงเมื่อมีงานในขอบเขตสิทธิ์ของคุณ" />}
  </WorkScreenShell>;
}
